# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compile_model_ <- function(modfile, use_dll, dll_dir) {
    .Call('dynmdl_compile_model_', PACKAGE = 'dynmdl', modfile, use_dll, dll_dir)
}

compute_derivatives <- function(modfile) {
    .Call('dynmdl_compute_derivatives', PACKAGE = 'dynmdl', modfile)
}

get_residuals_ <- function(endos, icols, exo_data, params, f_dynamic, n_endo, nper, max_lag) {
    .Call('dynmdl_get_residuals_', PACKAGE = 'dynmdl', endos, icols, exo_data, params, f_dynamic, n_endo, nper, max_lag)
}

get_triplet_jac <- function(endos, lead_lag_incidence, tshift, exo_data, params, jac_dynamic, n_endo, nper, max_lag) {
    .Call('dynmdl_get_triplet_jac', PACKAGE = 'dynmdl', endos, lead_lag_incidence, tshift, exo_data, params, jac_dynamic, n_endo, nper, max_lag)
}

get_jac_backwards <- function(endos, lags, cols, exo_data, params, jac_dynamic, it, max_lag) {
    .Call('dynmdl_get_jac_backwards', PACKAGE = 'dynmdl', endos, lags, cols, exo_data, params, jac_dynamic, it, max_lag)
}

run_macro <- function(modfile, new_modfile) {
    invisible(.Call('dynmdl_run_macro', PACKAGE = 'dynmdl', modfile, new_modfile))
}

