# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compile_model_ <- function(modfile, use_dll, dll_dir) {
    .Call(`_dynmdl_compile_model_`, modfile, use_dll, dll_dir)
}

compute_derivatives <- function(modfile) {
    .Call(`_dynmdl_compute_derivatives`, modfile)
}

get_residuals_ <- function(endos, icols, exo_data, params, f_dynamic, n_endo, nper, max_lag) {
    .Call(`_dynmdl_get_residuals_`, endos, icols, exo_data, params, f_dynamic, n_endo, nper, max_lag)
}

get_triplet_jac <- function(endos, lead_lag_incidence, tshift, exo_data, params, jac_dynamic, n_endo, nper, max_lag) {
    .Call(`_dynmdl_get_triplet_jac`, endos, lead_lag_incidence, tshift, exo_data, params, jac_dynamic, n_endo, nper, max_lag)
}

get_jac_backwards <- function(endos, lags, cols, exo_data, params, jac_dynamic, it, max_lag) {
    .Call(`_dynmdl_get_jac_backwards`, endos, lags, cols, exo_data, params, jac_dynamic, it, max_lag)
}

run_macro <- function(modfile, new_modfile) {
    invisible(.Call(`_dynmdl_run_macro`, modfile, new_modfile))
}

