# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compile_model_ <- function(modfile) {
    .Call('dynr_compile_model_', PACKAGE = 'dynr', modfile)
}

get_residuals_ <- function(endos, icols, exo_data, params, f_dynamic, n_endo, nper, max_lag) {
    .Call('dynr_get_residuals_', PACKAGE = 'dynr', endos, icols, exo_data, params, f_dynamic, n_endo, nper, max_lag)
}

get_triplet_jac <- function(endos, lead_lag_incidence, tshift, exo_data, params, f_dynamic, n_endo, nper, max_lag) {
    .Call('dynr_get_triplet_jac', PACKAGE = 'dynr', endos, lead_lag_incidence, tshift, exo_data, params, f_dynamic, n_endo, nper, max_lag)
}

