# This file is generated by 'tools/create_makedeps_files.R. Do not edit by hand!

MacroBison.o : ../FlexLexer.h location.hh MacroBison.hh MacroDriver.hh \
    MacroValue.hh position.hh stack.hh

MacroDriver.o : ../FlexLexer.h location.hh MacroBison.hh MacroDriver.hh \
    MacroValue.hh position.hh stack.hh

MacroFlex.o : ../FlexLexer.h location.hh MacroBison.hh MacroDriver.hh \
    MacroValue.hh position.hh stack.hh

MacroValue.o : ../FlexLexer.h location.hh MacroBison.hh MacroDriver.hh \
    MacroValue.hh position.hh stack.hh

