# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compile_model_ <- function(modfile) {
    .Call('dynr_compile_model_', PACKAGE = 'dynr', modfile)
}

get_residuals_ <- function(mdl, endos, icols) {
    .Call('dynr_get_residuals_', PACKAGE = 'dynr', mdl, endos, icols)
}

get_triplet_jac <- function(mdl, endos) {
    .Call('dynr_get_triplet_jac', PACKAGE = 'dynr', mdl, endos)
}

