#
# Functions for script gendepend.R
#

#' Returns included header files in a C-file or another header file.
#'
#' @param filename Character of length 1: the relative path of the file (relative
#' to `src_dir`).
#' @param src_dir The directory with source files (pkg_src_dir) 
#'
#' @return A character vector with the names of the included header files 
#' (the relative path with respect to `src_dir`), or `NULL` if the files not
#' have any dependencies.
#' 
#' @noRd
read_includes <- function(filename, src_dir) {
  src_path <- file.path(src_dir, filename)
  
  lines <- readLines(src_path, warn = FALSE)
  if (length(lines) == 0L) return(NULL)
  
  # Lines that look like include directives (quick filter)
  inc_lines <- grep("^\\s*#\\s*include\\s+", lines, value = TRUE, perl = TRUE)
  if (length(inc_lines) == 0L) return(NULL)
  
  # Quoted includes: #include "some/path.h"
  quoted <- grep('^\\s*#\\s*include\\s+"([^"]+)"', inc_lines, value = TRUE,
                 perl = TRUE) 
  if (length(quoted) > 0) {
    quoted <- sub('^\\s*#\\s*include\\s+"([^"]+)".*$', "\\1",
                  quoted, perl = TRUE)
  }
  
  # Special-case FlexLexer.h in angle brackets: #include <FlexLexer.h>
  flex_mask <- grepl("<\\s*FlexLexer\\.h\\s*>", inc_lines, perl = TRUE)
  flex <- if (any(flex_mask)) "FlexLexer.h" else character(0)
  
  # If the source file is inside macro/, prefix quoted includes that are not already prefixed
  if (startsWith(filename, "macro/") && length(quoted) > 0L) {
    pref_mask <- startsWith(quoted, "macro/")
    quoted[!pref_mask] <- paste0("macro/", quoted[!pref_mask])
  }
  
  # Keep quoted includes only if they exist under src_dir (preserve original behavior)
  if (length(quoted) > 0L) {
    exists_mask <- file.exists(file.path(src_dir, quoted))
    quoted <- quoted[exists_mask]
  }
  
  # Combine and return unique includes in encounter order
  includes <- c(quoted, flex)
  if (length(includes) == 0L) return(NULL)
  includes <- unique(includes)
  return(includes)
}

get_dep_list <- function(deps, filenames, src_dir) {
  
  deps <- lapply(filenames, FUN = read_includes, src_dir = src_dir)
  names(deps) <- filenames

  # remove files wiithout dependencies
  is_null <- sapply(deps, FUN = is.null)
  return(deps[!is_null])
}

#' Write a dependency file for a Makefile
#'
#' @param src_files Name of the source files (.cc files).
#' @param dep_file Character: name of the dependency file.
#' @param g An `igraph` object with dependency information.
#' @param is_macro Logical (default `FALSE`): `TRUE` if the sources files
#' are in directory `src/macro`.
#'
#' @noRd
write_dep_file <- function(src_files, dep_file, g, is_macro = FALSE) {
  con <- file(dep_file, "wt")
  writeLines(
    "# This file is generated by 'tools/create_makedeps_files.R. Do not edit by hand!\n",
    con = con
  )
  for (src_file in src_files) {
    src_name <- tools::file_path_sans_ext(src_file)
    if (is_macro) src_name <- basename(src_name)
    obj_file <- paste0(src_name, ".o")
    deps <- names(subcomponent(g, src_file, mode = "in")[-1])
    if (is_macro) {
      deps <- ifelse(
        startsWith(deps, "macro/"),
        basename(deps),
        file.path("..", deps, fsep = "/")
      )
    }
    deps <- sort(deps)
    txt <- paste(obj_file, ":", paste(deps, collapse = " "))
    lines <- strwrap(txt, width = 80, exdent = 4)
    nlines <- length(lines)
    if (nlines > 1) {
      nrs <- 1 : (nlines - 1)
      lines[nrs] <- paste(lines[nrs], "\\")
    }
    writeLines(c(lines, ""), con = con)
  }
  close(con)
  
  invisible()
}
