# This scripts creates a Makefile with dependencies of source files in
# directory pkg/src on the header files in directory pkg/src and
# "pkg/src/macro"/

library(igraph)
library(tictoc)

rm(list = ls())

source("tools/parameters.R")

deps <- readRDS(dep_rds)

tic("construct matrix")
all_names <- sort(union(names(deps), unique(unlist(deps))))
n <- length(all_names)
dep_mat <- matrix(0, nrow = n, ncol = n,
                  dimnames = list(all_names, all_names))
for (naam in names(deps)) {
  for (dep in deps[[naam]]) {
    dep_mat[naam, dep] <- 1
  }
}
toc()

tic("create graph")
g <- graph_from_adjacency_matrix(t(dep_mat))
toc()

# TODO: give a warning about include files  that are not used

# Write dependency files for the Makefiles -------------------

#' Write a dependency file for a Makefile
#'
#' @param src_files Name of the source files (.cc files).
#' @param dep_file Character: name of the dependency file.
#' @param is_macro Logical (default `FALSE`): `TRUE` is the sources files
#' are in directory `src/macro`.
#'
#' @noRd
write_dep_file <- function(src_files, dep_file, is_macro = FALSE) {
  con <- file(dep_file, "wt")
  writeLines(
    "# This file is generated by 'make makedeps'; do not edit by hand!\n",
    con = con
  )
  for (src_file in src_files) {
    src_name <- tools::file_path_sans_ext(src_file)
    if (is_macro) src_name <- basename(src_name)
    obj_file <- paste0(src_name, ".o")
    deps <- names(subcomponent(g, src_file, mode = "in")[-1])
    if (is_macro) {
      deps <- ifelse(
        startsWith(deps, "macro/"),
        basename(deps),
        file.path("..", deps, fsep = "/")
      )
    }
    deps <- sort(deps)
    txt <- paste(obj_file, ":", paste(deps, collapse = " "))
    lines <- strwrap(txt, width = 80, exdent = 4)
    nlines <- length(lines)
    if (nlines > 1) {
      nrs <- 1 : (nlines - 1)
      lines[nrs] <- paste(lines[nrs], "\\")
    }
    writeLines(c(lines, ""), con = con)
  }
  close(con)
}

tic("writing dep_file")

src_pattern <- paste0("\\.(",  paste(src_ext, collapse = "|"), ")$")
src_files <- grep(src_pattern, names(deps), value = TRUE)
src_files <- sort(src_files)

is_macro_file <- startsWith(src_files, "macro/")

write_dep_file(
  src_files = src_files[!is_macro_file],
  dep_file = dep_file
)
write_dep_file(
  src_files = src_files[is_macro_file],
  dep_file = dep_file_macro,
  is_macro = TRUE
)

toc()
