// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compile_model_
Rcpp::List compile_model_(std::string modfile);
RcppExport SEXP dynr_compile_model_(SEXP modfileSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type modfile(modfileSEXP);
    __result = Rcpp::wrap(compile_model_(modfile));
    return __result;
END_RCPP
}
// get_residuals_
NumericVector get_residuals_(S4 mdl, NumericVector endos, NumericVector icols);
RcppExport SEXP dynr_get_residuals_(SEXP mdlSEXP, SEXP endosSEXP, SEXP icolsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endos(endosSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type icols(icolsSEXP);
    __result = Rcpp::wrap(get_residuals_(mdl, endos, icols));
    return __result;
END_RCPP
}
// get_triplet_jac
List get_triplet_jac(S4 mdl, NumericVector endos);
RcppExport SEXP dynr_get_triplet_jac(SEXP mdlSEXP, SEXP endosSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endos(endosSEXP);
    __result = Rcpp::wrap(get_triplet_jac(mdl, endos));
    return __result;
END_RCPP
}
