// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compile_model_
Rcpp::List compile_model_(std::string modfile);
RcppExport SEXP dynr_compile_model_(SEXP modfileSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type modfile(modfileSEXP);
    __result = Rcpp::wrap(compile_model_(modfile));
    return __result;
END_RCPP
}
