# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compile_model_ <- function(modfile) {
    .Call('dynr_compile_model_', PACKAGE = 'dynr', modfile)
}

get_triplet_jac <- function(mdl_, endos, jacfun) {
    .Call('dynr_get_triplet_jac', PACKAGE = 'dynr', mdl_, endos, jacfun)
}

