# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compile a Dynare Model
#'
#' @param modfile The name of the model
#' @export
compile_model <- function(modfile) {
    .Call('dynparse_compile_model', PACKAGE = 'dynparse', modfile)
}

